networks:
    inception:
      driver: bridge

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  portainer_data:
    driver: local

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    depends_on: # start when mariadb and wordpress are ready
      mariadb:
        condition: service_healthy
      wordpress:
        condition: service_started
      portainer:
        condition: service_started
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    restart: always
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    restart: always
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p${SQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 5
      #start_period: 30s
      timeout: 5s

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    restart: always
    networks:
      - inception

  go-web:
    build: ./requirements/go-web
    container_name: go-web
    ports:
      - "8080:8080"
    networks:
      - inception

  ftp:
    build: ./requirements/ftp
    container_name: ftp
    ports:
      - "2121:2121"
      - "21100-21110:21100-21110"
    volumes:
      - wordpress_data:/home/$FTP_USER
    restart: always
    env_file:
      - .env
    networks:
      - inception

  redis:
    build: ./requirements/redis
    container_name: redis
    restart: always
    networks:
      - inception

  adminer:
    build: ./requirements/adminer
    container_name: adminer
    ports:
      - "8082:8081"
    restart: always
    networks:
      - inception

  portainer:
    build: ./requirements/portainer
    container_name: portainer
    ports:
      - "9443:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - inception